springfox:
   documentation:
       swagger:
          v2:
             path: /swagger.json

endpoints:
  enabled: false
  health:
    enabled: true
  info:
    enabled: true

server:
    port: 8085
    session:
        timeout: 450

spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB